# Generated by Django 5.2.8 on 2025-12-04 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminlogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adminlogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('cert_id', models.AutoField(primary_key=True, serialize=False)),
                ('cert_name', models.CharField(max_length=100)),
                ('issuing_organization', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
            ],
            options={
                'db_table': 'certification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('cgpa', models.DecimalField(db_column='CGPA', decimal_places=2, max_digits=3)),
                ('year_of_completion', models.IntegerField()),
            ],
            options={
                'db_table': 'education',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predictionhistory',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_roles', models.CharField(max_length=255)),
                ('confidence_scores', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'predictionhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'App User',
                'verbose_name_plural': 'App Users',
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('training_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('skills', models.TextField(help_text='Comma-separated skills')),
                ('certifications', models.TextField(help_text='Comma-separated certifications')),
                ('target_job_role', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.user')),
            ],
            options={
                'db_table': 'skills',
                'managed': True,
            },
        ),
    ]
