# Generated by Django 5.2.8 on 2025-12-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPlacement',
            fields=[
                ('placement_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('placement_type', models.CharField(choices=[('Job', 'Job'), ('Internship', 'Internship')], max_length=20)),
                ('date_of_joining', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='users.user')),
            ],
            options={
                'db_table': 'job_placements',
                'managed': True,
            },
        ),
    ]
