# Generated by Django 5.2.8 on 2025-12-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'App User', 'verbose_name_plural': 'App Users'},
        ),
    ]
