# Generated by Django 5.2.8 on 2025-12-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_banner_image_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_tour',
            field=models.BooleanField(default=False),
        ),
    ]
