# Generated by Django 5.2.8 on 2025-12-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_has_seen_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_seen_tour',
        ),
    ]
