# Generated by Django 5.2.8 on 2025-12-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_has_seen_tour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'managed': True},
        ),
    ]
