# Generated by Django 5.2.8 on 2025-12-19 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_education_options'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='education',
                    name='user',
                    field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
                    preserve_default=False,
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='education',
            name='cgpa',
            field=models.CharField(db_column='CGPA', max_length=255),
        ),
    ]
