# Generated by Django 5.2.8 on 2025-12-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_education_user_alter_education_cgpa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionhistory',
            options={'managed': True},
        ),
    ]
