# Generated by Django 5.2.8 on 2025-12-20 04:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_predictionhistory_options'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='predictionhistory',
        #     name='user',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='confidence_scores',
            field=models.TextField(help_text='JSON list of scores or full prediction object'),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='predicted_roles',
            field=models.TextField(help_text='JSON list of roles'),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
