# Generated by Django 5.2.8 on 2025-12-20 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_predictionhistory_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
