# Generated by Django 5.2.8 on 2025-12-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_predictionhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='specialization',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=255),
        ),
    ]
