# Generated by Django 5.2.8 on 2025-12-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_education_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_type', models.CharField(choices=[('regular', 'Regular'), ('skill', 'Skill Share'), ('prediction', 'Prediction Share')], default='regular', max_length=20)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.user')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
