# Generated by Django 5.2.8 on 2025-12-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
