# Generated by Django 5.2.8 on 2025-12-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='corrected_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
