# Generated by Django 5.2.8 on 2026-01-11 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_manual_fix_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlogs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='users.user')),
            ],
            options={
                'db_table': 'support_tickets',
                'managed': True,
            },
        ),
    ]
