# Generated by Django 5.2.8 on 2026-01-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_adminlogs_options_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='users.user'),
        ),
    ]
