# Generated by Django 5.2.8 on 2026-01-11 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_notification_ticketchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.ticketchat')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to='users.user')),
            ],
            options={
                'db_table': 'chat_reports',
                'managed': True,
            },
        ),
    ]
