# Generated by Django 5.2.8 on 2026-01-14 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
    ]
