# Generated by Django 5.2.8 on 2026-01-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketchat',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/'),
        ),
    ]
