# Generated by Django 5.2.8 on 2026-01-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hire_now',
            field=models.BooleanField(default=False, help_text='Available for hire (Prime only)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='prime_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
