# Generated by Django 5.2.8 on 2026-03-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_hire_now_user_is_prime_user_prime_expiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlogs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'managed': True},
        ),
    ]
